GreatKart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),

    # ORDERS
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetpassword/validate/<uidb64>/<token>', views.resetpassword_validate, name='resetpassword_validate'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),
    path('', views.dashboard, name='dashboard'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('increase/<int:cart_item_id>', views.increase, name='increase'),
    path('remove_cart/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('checkout/', views.checkout, name='checkout')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

# Create your models here.

class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError('User must have an email address')

        if not username:
            raise ValueError('User must have username')

        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, email, username, password):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password = password,
            first_name = first_name,
            last_name = last_name,
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    first_name      = models.CharField(max_length=50)
    last_name       = models.CharField(max_length=50)
    username        = models.CharField(max_length=50, unique=True)
    email           = models.EmailField(max_length=100, unique=True)
    phone_number    = models.CharField(max_length=50)

    # required
    date_joined     = models.DateTimeField(auto_now_add=True)
    last_login      = models.DateTimeField(auto_now_add=True)
    is_admin        = models.BooleanField(default=False)
    is_staff        = models.BooleanField(default=False)
    is_active       = models.BooleanField(default=False)
    is_superadmin   = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = MyAccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def has_module_perms(self, add_label):
        return True


class UserProfile(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE)
    address_line_1 = models.CharField(blank=True, max_length=100)
    address_line_2 = models.CharField(blank=True, max_length=100)
    profile_picture = models.ImageField(blank=True, upload_to='userprofile')
    city = models.CharField(blank=True, max_length=20)
    state = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)

    def __str__(self):
        return self.user.full_name()

    def full_address(self):
        return f'{self.address_line_1}, {self.address_line_2}'

accounts/forms.py
from django import forms
from.models import Account, UserProfile


class RegistrationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter First Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter Last Name'
        self.fields['phone_number'].widget.attrs['placeholder'] = 'Enter Phone Number'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter Email'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'phone_number', 'email', 'password']

    password = forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder': 'Enter Password'
        }))

    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder': 'Confirm Password'
        }))

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError('Password does not match!')


class UserForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('first_name', 'last_name', 'phone_number')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False, error_messages={'invalid':('Image files only')}, widget=forms.FileInput)
    class Meta:
        model = UserProfile
        fields = ('address_line_1', 'address_line_2', 'city', 'state', 'country', 'profile_picture')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

accounts/views.py
from django.contrib import messages, auth
from .models import Account, UserProfile
from carts.models import Cart, Cart_item
from orders.models import Order
from carts.views import _cart_id
from django.shortcuts import render, redirect, reverse, get_object_or_404
from.forms import RegistrationForm, UserForm, UserProfileForm
from django.contrib.auth.decorators import login_required
import requests

# Verification email
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage

# Create your views here.


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            phone_number = form.cleaned_data['phone_number']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            username = email.split('@')[0]
            user = Account.object.create_user(first_name=first_name, last_name=last_name, email=email, username=username, password=password)
            user.phone_number = phone_number
            user.save()

            # USER ACTIVATION
            current_site = get_current_site(request)
            mail_subject = 'Please activate your account'
            message = render_to_string('accounts/account_verification_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()

#            messages.success(request, 'Thank you for registering. We have sent you a verification email. Please verify!')
            return redirect('/accounts/login/?command=verification&email=' + email)
    else:
        form = RegistrationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/register.html', context)

def login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        user = auth.authenticate(email=email, password=password)
        if user is not None:
            try:
                cart = Cart.objects.get(cart_id=_cart_id(request))
                is_cart_item_exists = Cart_item.objects.filter(cart=cart).exists()
                if is_cart_item_exists:
                    cart_item = Cart_item.objects.filter(cart=cart)
                    product_variations = []
                    # Getting the product variation by cart_id
                    for item in cart_item:
                        variation = item.variations.all()
                        product_variations.append(list(variation))
                        # Get the cart items from the user to access his product variation
                    cart_item = Cart_item.objects.filter(user=user)
                    ex_var_list = []
                    id = []
                    for item in cart_item:
                        variation_color_size = list(item.variations.colors())
                        variation_color_size.extend(list(item.variations.sizes()))
                        ex_var_list.append(variation_color_size)
                        id.append(item.id)

                    for pr in product_variations:
                        if pr in ex_var_list:
                            index = ex_var_list.index(pr)
                            item_id = id[index]
                            item = Cart_item.objects.get(id=item_id)
                            item.quantity += 1
                            item.save()
                        else:
                            cart_item = Cart_item.objects.filter(cart=cart)
                            for item in cart_item:
                                item.user = user
                                item.save()

            except:
                pass
            auth.login(request, user)
            messages.success(request, 'You are now logged in.')
            url = request.META.get('HTTP_REFERER')
            try:
                query = requests.utils.urlparse(url).query # query = '?'next=/cart/checkout/
                params = dict(x.split('=') for x in query.split('&'))
                if 'next' in params:
                    nextPage = params['next']
                    return redirect(nextPage)
            except:
                return redirect('accounts:dashboard')
        else:
            messages.error(request, 'Invalid login credentials!')
            return redirect('accounts:login')
    return render(request, 'accounts/login.html')


@login_required(login_url='accounts:login')
def logout(request):
    auth.logout(request)
    messages.success(request, 'You\'re logged out!')
    return redirect('accounts:login')

def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Congratulations! Your account is activated.')
        return redirect('accounts:login')
    else:
        messages.error(request, 'Invalid activation link!')
        return redirect('accounts:register')

@login_required(login_url='accounts:login')
def dashboard(request):
    orders = Order.objects.order_by('-created_at').filter(user_id=request.user.id, is_ordered=True)
    orders_count = orders.count()
    context = {
        'orders_count': orders_count
    }
    return render(request, 'accounts/dashboard.html', context)

def forgotPassword(request):
    if request.method == 'POST':
        email = request.POST['email']
        if Account.objects.filter(email=email).exists():
            user = Account.objects.get(email__exact=email)

            # Reset password email
            current_site = get_current_site(request)
            mail_subject = 'Reset your password'
            message = render_to_string('accounts/reset_password_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()

            messages.success(request, 'Password reset email has been sent to your email address.')
            return redirect('accounts:login')
        else:
            messages.error(request, 'Account does not exist!')
            return redirect('accounts:forgotPassword')

    return render(request, 'accounts/forgotPassword.html')

def resetpassword_validate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session['uid'] = uid
        messages.success(request, 'Please reset your password.')
        return redirect('accounts:resetPassword')
    else:
        messages.error(request, 'This link has been expired!')
        return redirect('accounts:resetPassword')

def resetPassword(request):
    if request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            uid = request.session.get('uid')
            user = Account.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request, 'Password reset successful.')
            return redirect('accounts:login')
        else:
            messages.error(request, 'Password do not match!')
            return redirect('accounts:resetPassword')
    else:
        return render(request, 'accounts/resetPassword.html')

def my_orders(request):
    orders = Order.objects.filter(user=request.user, is_ordered=True).order_by('-created_at')
    context = {
        'orders': orders
    }
    return render(request, 'accounts/my_orders.html', context)

def edit_profile(request):
    user_profile = get_object_or_404(UserProfile, user=request.user)
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile has been updated.')
            return redirect('accounts:edit_profile')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = UserProfileForm(instance=user_profile)
    context = {
        'user_form': user_form,
        'profile_form': profile_form,
        'user_profile': user_profile,
    }
    return render(request, 'accounts/edit_profile.html', context)

templates/accounts/account_verification_email.html
{% autoescape off %}

Hi {{ user.first_name }},

Please click on below link to confirm your registration:
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}

If you think it's not you, please ignore this email!

{% endautoescape %}

templates/accounts/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">
{% include 'includes/alerts.html' %}
<div class="container">
	<div class="row">
    {% include 'includes/dashboard_sidebar.html' %}
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Logged in as:</strong>
			<span>{{ user.full_name }}</span>
		</header>
		<div class="card-body">
			<div class="row"> 

                <div class="col-md-6">
                    <div class="card" style="text-align: center">
                        <div class="card-body">
                            <h5 class="card-title">Total orders</h5>
                            <h4>{{ orders_count }}</h4>
                            <a href="">View Orders</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card" style="text-align: center">
                        <div class="card-body">
                            <img src="https://www.w3schools.com/howto/img_avatar.png" alt="User Profile Picture" width="50" height="50" style="border-radius: 50%" class="avatar">
                            <p class="mb-0">{{ user.email }}</p>
                            <p>{{ user.phone_number }}</p>
                        </div>
                    </div>
                </div>

			</div> <!-- row.// -->
		</div> <!-- card-body .// -->

		</article> <!-- order-group.// --> 
	</main>
</div> <!-- row.// -->
</div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">
{% include 'includes/alerts.html' %}
<div class="container">
	<div class="row">
    {% include 'includes/dashboard_sidebar.html' %}
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Edit your profile</strong>
		</header>
		<div class="card-body">
            <div class="text-right">
                <img src="{{ user_profile.profile_picture.url }}" alt="Profile Picture" width="100" height="100" style="border-radius: 50%">
            </div>
			<div class="row">
                <div class="col-md-12">
                    <form action="{% url 'accounts:edit_profile' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label>First Name</label>
                                {{ user_form.first_name }}
                            </div>
                            <div class="form-group col-md-6">
                                <label>Last Name</label>
                                {{ user_form.last_name }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label>Phone Number</label>
                                {{ user_form.phone_number }}
                            </div>
                            <div class="form-group col-md-6">
                                <label>Profile picture</label>
                                {{ profile_form.profile_picture }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Address Line 1</label>
                            {{ profile_form.address_line_1 }}
                        </div>
                        <div class="form-group">
                            <label>Address Line 2</label>
                            {{ profile_form.address_line_2 }}
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label>City</label>
                                {{ profile_form.city }}
                            </div>
                            <div class="form-group col-md-4">
                                <label>State</label>
                                {{ profile_form.state }}
                            </div>
                            <div class="form-group col-md-4">
                                <label>Country</label>
                                {{ profile_form.country }}
                            </div>
                        </div>
                        <input type="submit" value="save" class="btn btn-primary">
                    </form>
                </div>
			</div> <!-- row.// -->
		</div> <!-- card-body .// -->

		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->
</div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/accounts/forgotPassword.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y" style="min-height:84vh">

<!-- ============================ COMPONENT LOGIN   ================================= -->
	<div class="card mx-auto" style="max-width: 600px; margin-top:100px;">
      <div class="card-body">
      <h4 class="card-title mb-4">Forgot Password</h4>
          {% include 'includes/alerts.html' %}
      <form action="{% url 'accounts:forgotPassword' %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
			 <input type="email" class="form-control" placeholder="Email Address" name="email" >
          </div> <!-- form-group// -->
          
          <div class="form-group">
          	<a href="{% url 'accounts:login' %}" class="float-right">Got password? Login</a>
          </div> <!-- form-group form-check .// -->
          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block"> Submit  </button>
          </div> <!-- form-group// -->    
      </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->

     <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
     <br><br>
<!-- ============================ COMPONENT LOGIN  END.// ================================= -->

</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y" style="min-height:84vh">

<!-- ============================ COMPONENT LOGIN   ================================= -->
    {% if request.GET.command == 'verification' %}
        <div class="container mx-auto alert alert-info text-center" role="alert" style="max-width: 1024px; margin-top:100px;">
            Thank you for registering. We have sent you a verification email to {{ request.GET.email }}. Please verify it!
            <br><br>
            Already verified? <a href="{% url 'accounts:login' %}">Login</a>
        </div>
    {% else %}


	<div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
      <div class="card-body">
      <h4 class="card-title mb-4">Sign in</h4>
        {% include 'includes/alerts.html' %}
      <form action="{% url 'accounts:login' %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
			 <input type="email" class="form-control" placeholder="Email Address" name="email" >
          </div> <!-- form-group// -->
          <div class="form-group">
			<input type="password" class="form-control" placeholder="Password" name="password" >
          </div> <!-- form-group// -->
          
          <div class="form-group">
          	<a href="#" class="float-right">Forgot password?</a> 
           
          </div> <!-- form-group form-check .// -->
          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block"> Login  </button>
          </div> <!-- form-group// -->    
      </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->

     <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
     <br><br>
<!-- ============================ COMPONENT LOGIN  END.// ================================= -->
{% endif %}

</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/accounts/my_orders.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">
{% include 'includes/alerts.html' %}
<div class="container">
	<div class="row">
    {% include 'includes/dashboard_sidebar.html' %}
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Your order history</strong>
		</header>
		<div class="card-body">
			<div class="row">
                <div class="col-md-12">
                    <table class="table table-hover">
                      <thead>
                        <tr>
                          <th scope="col">Order #</th>
                          <th scope="col">Billing Name</th>
                          <th scope="col">Phone</th>
                          <th scope="col">Order Total</th>
                          <th scope="col">Date</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for order in orders %}
                        <tr>
                          <th scope="row">{{ order.order_number }}</th>
                          <td>{{ order.full_name }}</td>
                          <td>{{ order.phone }}</td>
                          <td>${{ order.order_total }}</td>
                          <td>{{ order.created_at }}</td>
                        </tr>
                      {% endfor %}
                      </tbody>
                    </table>
                </div>
			</div> <!-- row.// -->
		</div> <!-- card-body .// -->

		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->
</div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">

<!-- ============================ COMPONENT REGISTER   ================================= -->
	<div class="card mx-auto" style="max-width:520px; margin-top:40px;">
      <article class="card-body">
          {% include 'includes/alerts.html' %}
		<header class="mb-4"><h4 class="card-title">Sign up</h4></header>
		<form action="{% url 'accounts:register' %}" method="POST">
            {% csrf_token %}
				<div class="form-row">
					<div class="col form-group">
						<label>First name</label>
                        {{ form.first_name }}
					</div> <!-- form-group end.// -->
					<div class="col form-group">
						<label>Last name</label>
                        {{ form.last_name }}
					</div> <!-- form-group end.// -->
				</div> <!-- form-row end.// -->
				<div class="form-row">
                    <div class="form-group col-md-6">
					  <label>Email</label>
                        {{ form.email }}
					</div> <!-- form-group end.// -->
					<div class="form-group col-md-6">
					  <label>Phone Number</label>
                        {{ form.phone_number }}
					</div> <!-- form-group end.// -->
				</div> <!-- form-row.// -->
				<div class="form-row">
					<div class="form-group col-md-6">
						<label>Create password</label>
					    {{ form.password }}
					</div> <!-- form-group end.// --> 
					<div class="form-group col-md-6">
						<label>Repeat password</label>
                            {{ form.confirm_password }}
					</div> <!-- form-group end.// -->  
				</div>
			    <div class="form-group">
			        <button type="submit" class="btn btn-primary btn-block"> Register  </button>
			    </div> <!-- form-group// -->      
              {{ form.email.errors }}
              {{ form.non_field_errors }}
			</form>
		</article><!-- card-body.// -->
    </div> <!-- card .// -->
    <p class="text-center mt-4">Have an account? <a href="{% url 'accounts:login' %}">Log In</a></p>
    <br><br>
<!-- ============================ COMPONENT REGISTER  END.// ================================= -->


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/accounts/reset_password_email.html
{% autoescape off %}

Hi {{ user.first_name }},

As requested, please click below link to reset your password:
http://{{ domain }}{% url 'accounts:resetpassword_validate' uidb64=uid token=token %}

If you think it's not you, please ignore this email!

{% endautoescape %}