GreatKart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),

    # ORDERS
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetpassword/validate/<uidb64>/<token>', views.resetpassword_validate, name='resetpassword_validate'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),
    path('', views.dashboard, name='dashboard'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('increase/<int:cart_item_id>', views.increase, name='increase'),
    path('remove_cart/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('checkout/', views.checkout, name='checkout')
]

store/urls.py
from django.urls import path
from . import views


app_name = 'store'
urlpatterns = [
    path('', views.store, name='store'),
    path('search/', views.search, name='search'),
    path('<slug:category_slug>/', views.store, name='products_by_category'),
    path('<slug:category_slug>/<slug:product_slug>', views.product_detail, name='product_detail'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),
]

templates/includes/alerts.html
{% load static %}
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container">
            <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

templates/includes/dashboard_sidebar.html
    <aside class="col-md-3">
		<!--   SIDEBAR   -->
		<ul class="list-group">
			<a class="list-group-item{% if '/accounts/' == request.path %} active{% endif %}" href="{% url 'accounts:dashboard' %}"> Dashboard</a>
			<a class="list-group-item{% if '/my_orders/' in request.path %} active{% endif %}" href="{% url 'accounts:my_orders' %}"> My Orders </a>
			<a class="list-group-item{% if '/edit_profile/' in request.path %} active{% endif %}" href="{% url 'accounts:edit_profile' %}"> Edit Profile </a>
			<a class="list-group-item{% if '/change_password/' in request.path %} active{% endif %}" href="{% url 'accounts:resetPassword' %}"> Change Password </a>
		</ul>
		<br>
		<a class="btn btn-light btn-block" href="{% url 'accounts:logout' %}"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a>
		<!--   SIDEBAR .//END   -->
	</aside>

templates/includes/footer.html
<!-- ========================= FOOTER ========================= -->
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-2">
				<p class="text-muted"> &copy 2022 Super Store </p>
			</div>
			<div class="col-md-8 text-md-center">
				<span  class="px-2">hristogemedzhiev@gmail.com</span>
				<span  class="px-2">+359896733031</span>
				<span  class="px-2">Burgas 11 str.</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->

templates/includes/navbar.html
{% load static %}

<header class="section-header">


<section class="header-main border-bottom">
	<div class="container">
<div class="row align-items-center">
	<div class="col-lg-2 col-md-3 col-6">
		<a href="/" class="brand-wrap">
			<img class="logo" src="{% static '/images/logo.png' %}">
		</a> <!-- brand-wrap.// -->
	</div>
	<div class="col-lg col-sm col-md col-6 flex-grow-0">
		<div class="category-wrap dropdown d-inline-block float-right">
			<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
				<i class="fa fa-bars"></i> All category
			</button>
			<div class="dropdown-menu">
                {% for cat in links %}
				<a class="dropdown-item" href="{% url 'store:products_by_category' cat.slug %}">{{ cat.category_name }}</a>
                {% endfor %}
			</div>
		</div>  <!-- category-wrap.// -->
	</div> <!-- col.// -->
	<a href="{% url 'store:store' %}" class="btn btn-outline-primary">Store</a>
	<div class="col-lg  col-md-6 col-sm-12 col">
		<form action="{% url 'store:search' %}" class="search" method="GET">
			<div class="input-group w-100">
			    <input name="keyword" type="text" class="form-control" style="width:60%;" placeholder="Search">

			    <div class="input-group-append">
			      <button class="btn btn-primary" type="submit">
			        <i class="fa fa-search"></i>
			      </button>
			    </div>
		    </div>
		</form> <!-- search-wrap .end// -->
	</div> <!-- col.// -->
	<div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
				<div class="d-flex justify-content-end mb-3 mb-lg-0">
                    {% if user.id is None %}
                        <div class="widget-header">
                            <small class="title text-muted">Welcome guest!</small>
                            <div>
                                <a href="{% url 'accounts:login' %}">Sign in</a> <span class="dark-transp"> | </span>
                                <a href="{% url 'accounts:register' %}"> Register</a>
                            </div>
                        </div>
                    {% else %}
                        <div class="widget-header">
                            <small class="title text-muted">Welcome {{ user.first_name }}!</small>
                            <div>
                                <a href="{% url 'accounts:dashboard' %}">Dashboard</a> <span class="dark-transp"> | </span>
                                <a href="{% url 'accounts:logout' %}"> Logout</a>
                            </div>
                        </div>
                    {% endif %}
					<a href="{% url 'carts:cart' %}" class="widget-header pl-3 ml-3">
						<div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
						<span class="badge badge-pill badge-danger notify">{{ cart_count }}</span>
					</a>
				</div> <!-- widgets-wrap.// -->

			</div> <!-- col.// -->
</div> <!-- row.// -->
	</div> <!-- container.// -->
</section> <!-- header-main .// -->

</header> <!-- section-header.// -->