GreatKart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),

    # ORDERS
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetpassword/validate/<uidb64>/<token>', views.resetpassword_validate, name='resetpassword_validate'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),
    path('', views.dashboard, name='dashboard'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('increase/<int:cart_item_id>', views.increase, name='increase'),
    path('remove_cart/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('checkout/', views.checkout, name='checkout')
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('place_order/', views.place_order, name='place_order'),
    path('payments/', views.payments, name='payments'),
    path('order_complete/', views.order_complete, name='order_complete')
]

store/urls.py
from django.urls import path
from . import views


app_name = 'store'
urlpatterns = [
    path('', views.store, name='store'),
    path('search/', views.search, name='search'),
    path('<slug:category_slug>/', views.store, name='products_by_category'),
    path('<slug:category_slug>/<slug:product_slug>', views.product_detail, name='product_detail'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),
]

carts/models.py
from django.db import models
from store.models import Product, Variations
from accounts.models import Account

# Create your models here.


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class Cart_item(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variations, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product.product_name

store/models.py
from django.db import models
from category.models import Category
from accounts.models import Account
from django.db.models import Avg, Count

# Create your models here.


class Product(models.Model):
    product_name        = models.CharField(max_length=200, unique=True)
    slug                = models.SlugField(max_length=200, unique=True)
    category            = models.ForeignKey(Category, on_delete=models.CASCADE)
    description         = models.TextField(max_length=500, blank=True)
    price               = models.DecimalField(decimal_places=2, max_digits=10)
    images              = models.ImageField(upload_to='photos/products')
    stock               = models.IntegerField()
    is_available        = models.BooleanField(default=True)
    created             = models.DateTimeField(auto_now_add=True)
    modified            = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product_name

    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count

class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)

variation_category_choice = (
    ('color', 'color'),
    ('size', 'size'),
)
class Variations(models.Model):
    product             = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category  = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value     = models.CharField(max_length=100)
    is_active           = models.BooleanField(default=True)
    created             = models.DateTimeField(auto_now=True)
    objects             = VariationManager()

    def __str__(self):
        return self.variation_value

    class Meta:
        verbose_name_plural = 'Variations'


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

store/forms.py
from django import forms
from .models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Product, Variations
from .models import Cart, Cart_item
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

# Create your views here.

def cart(request, total=0, quantity=0,grand_total=0, cart_item=None):
    context = {}
    try:
        if request.user.is_authenticated:
            cart_items = Cart_item.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = Cart_item.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += round((cart_item.product.price * cart_item.quantity), 2)
            quantity += cart_item.quantity
        tax = round(((2 * total)/100), 2)
        grand_total = round(total + tax, 2)
        context = {
            'total': total,
            'quantity': quantity,
            'tax': tax,
            'cart_items': cart_items,
            'grand_total': grand_total,
        }
    except:
        context = {'cart_items': False}
    return render(request, 'store/cart.html', context)

def _cart_id(request):
    cart_session = request.session.session_key
    if not cart_session:
        cart_session = request.session.create()
    return cart_session

def add_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id)
    if current_user.is_authenticated:
# IF THE USER IS AUTHENTICATED
        product_variation = []
        if request.method == 'POST':
            # Get the product variations in product_variations: Example(Color: Red, Size: Small)
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variations.objects.get(product=product, variation_category__iexact=key,
                                                       variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        is_cart_item_exists = Cart_item.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exists:
            # Get all cart_items of the given product
            cart_item = Cart_item.objects.filter(product=product, user=current_user)
            ex_var_list = []
            id = []

            for item in cart_item:
                # Look through each of the cart_items and save their variations in ex_var_list
                variation_color_size = list(item.variations.colors())
                variation_color_size.extend(list(item.variations.sizes()))
                ex_var_list.append(variation_color_size)
                # Save the cart_item id's for every ex_var_list variation
                id.append(item.id)
            print(ex_var_list, product_variation)
            if product_variation in ex_var_list:
                # Increase the cart item quantity
                # Get the index in the ex_var_list for the given product variations, and then getting the true cart_item id from the 'id' that we created earlier
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = Cart_item.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                # Create a new cart item
                item = Cart_item.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = Cart_item.objects.create(
                product=product,
                quantity=1,
                user=current_user
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('carts:cart')
    else:
# IF THE USER IS NOT AUTHENTICATED
        product_variation = []
        if request.method == 'POST':
            # Get the product variations in product_variations: Example(Color: Red, Size: Small)
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variations.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass
        try:
            # Open the existing cart or creating a new one
            cart = Cart.objects.get(cart_id=_cart_id(request)) # get the session id
        except Cart.DoesNotExist:
            cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()

        is_cart_item_exists = Cart_item.objects.filter(product=product, cart=cart).exists()

        if is_cart_item_exists:
            # Get all cart_items of the given product
            cart_item = Cart_item.objects.filter(product=product, cart=cart)
            ex_var_list = []
            id = []

            for item in cart_item:
                # Look through each of the cart_items and save their variations in ex_var_list
                variation_color_size = list(item.variations.colors())
                variation_color_size.extend(list(item.variations.sizes()))
                ex_var_list.append(variation_color_size)
                # Save the cart_item id's for every ex_var_list variation
                id.append(item.id)
            if product_variation in ex_var_list:
                # Increase the cart item quantity
                # Get the index in the ex_var_list for the given product variations, and then getting the true cart_item id from the 'id' that we created earlier
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = Cart_item.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                # Create a new cart item
                item = Cart_item.objects.create(product=product, quantity=1, cart=cart)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = Cart_item.objects.create(
                product = product,
                quantity = 1,
                cart = cart
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('carts:cart')

def increase(request, cart_item_id):
    cart_item = Cart_item.objects.get(id=cart_item_id)
    cart_item.quantity += 1
    cart_item.save()
    return redirect('carts:cart')

def remove_cart(request, cart_item_id):

    try:
        type = request.GET['type']
    except:
        type = ''
    if request.user.is_authenticated:
        cart_item = Cart_item.objects.get(user=request.user, id=cart_item_id, is_active=True)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = Cart_item.objects.get(id=cart_item_id, cart=cart)
    if type == 'delete':
        cart_item.delete()
    elif type == 'minus':
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    return redirect('carts:cart')

@login_required(login_url='accounts:login')
def checkout(request, total=0, quantity=0, cart_item=None):
    context = {}
    try:
        if request.user.is_authenticated:
            cart_items = Cart_item.objects.filter(user=request.user)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = Cart_item.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += round((cart_item.product.price * cart_item.quantity), 2)
            quantity += cart_item.quantity
        tax = round(((2 * total) / 100), 2)
        grand_total = round(total + tax, 2)
        context = {
            'total': total,
            'quantity': quantity,
            'tax': tax,
            'cart_items': cart_items,
            'grand_total': grand_total,
        }
    except:
        context = {'cart_items': False}
    return render(request, 'store/checkout.html', context)

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
{% if not cart_items %}
    <h2 class="text-center">Your Shopping Cart is Empty</h2>
    <br>
    <div class="text-center">
        <a href="{% url 'store:store' %}" class="btn btn-primary">Continue Shopping</a>
    </div>
{% else %}
<div class="row">
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>
{% for item in cart_items %}
<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><img src="{{ item.product.images.url }}" class="img-sm"></div>
			<figcaption class="info">
				<a href="{% url 'store:product_detail' item.product.category.slug item.product.slug %}" class="title text-dark">{{ item.product.product_name }}</a>
				<p class="text-muted small">
                    {% if item.variations.all %}
                        {% for cart_item in item.variations.all %}
                            {{ cart_item.variation_category | capfirst }} : {{ cart_item.variation_value | capfirst }} <br>
                        {% endfor %}
                    {% endif %}
                </p>
			</figcaption>
		</figure>
	</td>
	<td> 
		<!-- col.// -->
					<div class="col"> 
						<div class="input-group input-spinner">
							<div class="input-group-prepend">
							<a href="{% url 'carts:remove_cart' item.id %}?type=minus" class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-minus"></i> </a>
							</div>
                            <div class="text-dark b form-control text-center" type="text" ><strong>{{ item.quantity }}</strong></div>
							<div class="input-group-append">
							<a href="{% url 'carts:increase' item.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-plus"></i> </a>
							</div>
						</div> <!-- input-group.// -->
					</div> <!-- col.// -->
	</td>
	<td> 
		<div class="price-wrap"> 
			<var class="price">${{ item.sub_total }}</var>
			<small class="text-muted"> ${{ item.product.price }} each </small>
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right">
	<a href="{% url 'carts:remove_cart' item.id %}?type=delete" onclick="return confirm('Are you sure you want to delete this item?')" class="btn btn-danger"> Remove</a>
	</td>
</tr>
{% endfor %}
</tbody>
</table>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">${{ total }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right"> ${{ tax }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Total:</dt>
			  <dd class="text-right text-dark b"><strong>${{ grand_total }}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="{% static '/images/misc/payments.png' %}" height="26">
			</p>
			<a href="{% url 'carts:checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
			<a href="{% url 'store:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->
{% endif %}
<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/store/product-detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
<div class="card">
	<div class="row no-gutters">
		<aside class="col-md-6">
<article class="gallery-wrap"> 
	<div class="img-big-wrap">
	   <a href="#"><img src="{{ product.images.url }}"></a>
	</div> <!-- img-big-wrap.// -->
	
</article> <!-- gallery-wrap .end// -->
		</aside>
		<main class="col-md-6 border-left">

<form action="{% url 'carts:add_cart' product.id %}" method="POST">
{% csrf_token %}
<article class="content-body">
<h2 class="title">{{ product.product_name }}</h2>
    <div class="rating-star">
        <span>
            <i class="fa fa-star{% if product.averageReview < 0.5 %}-o{% elif product.averageReview >= 0.5 and product.averageReview < 1 %}-half-o{% endif %}"></i>
            <i class="fa fa-star{% if product.averageReview < 1.5 %}-o{% elif product.averageReview >= 1.5 and product.averageReview < 2 %}-half-o{% endif %}"></i>
            <i class="fa fa-star{% if product.averageReview < 2.5 %}-o{% elif product.averageReview >= 2.5 and product.averageReview < 3 %}-half-o{% endif %}"></i>
            <i class="fa fa-star{% if product.averageReview < 3.5 %}-o{% elif product.averageReview >= 3.5 and product.averageReview < 4 %}-half-o{% endif %}"></i>
            <i class="fa fa-star{% if product.averageReview < 4.5 %}-o{% elif product.averageReview >= 4.5 and product.averageReview < 5 %}-half-o{% endif %}"></i>
            <span>({{ product.countReview }})</span>
        </span>
    </div>
<div class="mb-3"> 
	<var class="price h4">${{ product.price }}</var>
</div> 

<p>{{ product.description }}</p>

<hr>
	<div class="row">
		<div class="item-option-select">
			<h6>Choose Color</h6>
			    <select class="form-control" name="color">
                    <option value="" disabled selected>Select</option>
                    {% for var in product.variations_set.colors %}
                        <option value="{{ var.variation_value | lower }}">{{ var.variation_value | capfirst }}</option>
                    {% endfor %}
                </select>
		</div>
	</div> <!-- row.// -->
	<div class="row">
		<div class="item-option-select">
			<h6>Select Size</h6>
			<select class="form-control" name="size">
                <option value="" disabled selected>Select</option>
                {% for var in product.variations_set.sizes %}
                    <option value="{{ var.variation_value | lower }}">{{ var.variation_value | capfirst }}</option>
                {% endfor %}
            </select>
		</div>
	</div> <!-- row.// -->
	<hr>
    {% if product.is_available == True and product.stock > 0 %}
        {% if in_cart %}
            <button type="submit" class="btn  btn-success"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i></button>
            <a href="{% url 'carts:cart' %}" class="btn btn-outline-primary"> <span class="text">View Cart</span> <i class="fas fa-eye"></i></a>
        {% else %}
	        <button type="submit" class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i></button>
        {% endif %}
    {% elif product.is_available == False %}
        <h5 class="text-danger">Unavailable</h5>
    {% elif product.stock <= 0 %}
        <h5 class="text-danger">Out of stock!</h5>
    {% endif %}
</article> <!-- product-info-aside .// -->
</form>
		</main> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- card.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

<br>

<div class="row">
			<div class="col-md-9">



    <form action="{% url 'store:submit_review' product.id %}" method="POST">
        {% csrf_token %}
        <h5>Write your review</h5>
        <div>
            <label>How do you rate this product?</label>
            <br>
            <div class="rate">
                <input type="radio" name="rating" id="rating10" value="5" required><label for="rating10" title="5"></label>
                <input type="radio" name="rating" id="rating9" value="4.5" required><label for="rating9" title="4.5" class="half"></label>
                <input type="radio" name="rating" id="rating8" value="4" required><label for="rating8" title="4"></label>
                <input type="radio" name="rating" id="rating7" value="3.5" required><label for="rating7" title="3.5" class="half"></label>
                <input type="radio" name="rating" id="rating6" value="3" required><label for="rating6" title="3"></label>
                <input type="radio" name="rating" id="rating5" value="2.5" required><label for="rating5" title="2.5" class="half"></label>
                <input type="radio" name="rating" id="rating4" value="2" required><label for="rating4" title="2"></label>
                <input type="radio" name="rating" id="rating3" value="1.5" required><label for="rating3" title="1.5" class="half"></label>
                <input type="radio" name="rating" id="rating2" value="1" required><label for="rating2" title="1"></label>
                <input type="radio" name="rating" id="rating1" value="0.5" required><label for="rating1" title="0.5" class="half"></label>
            </div>
<br>
            Review Title:
            <input type="text" class="form-control" name="subject">
            <br>
            Review:
            <textarea name="review" rows="4" class="form-control"></textarea>
            <br>
            {% if user.is_authenticated and is_purchased %}
                <input type="submit" value="Submit Review" class="btn btn-primary">
            {% elif not user.is_authenticated%}
                <p>You must be logged in to post a review. <span><a href="{% url 'accounts:login' %}">Login now</a> </span></p>
            {% elif not is_purchased %}
                <p>You must purchase the product to post a review.</p>
            {% endif %}
        </div>
        {% include 'includes/alerts.html' %}
    </form>
<br>

<header class="section-heading">
    <h3>Customer Reviews </h3>
    <div class="rating-star">
        <span>
            <i class="fa fa-star{% if product.averageReview < 0.5 %}-o{% elif product.averageReview >= 0.5 and product.averageReview < 1 %}-half-o{% endif %}"></i>
            <i class="fa fa-star{% if product.averageReview < 1.5 %}-o{% elif product.averageReview >= 1.5 and product.averageReview < 2 %}-half-o{% endif %}"></i>
            <i class="fa fa-star{% if product.averageReview < 2.5 %}-o{% elif product.averageReview >= 2.5 and product.averageReview < 3 %}-half-o{% endif %}"></i>
            <i class="fa fa-star{% if product.averageReview < 3.5 %}-o{% elif product.averageReview >= 3.5 and product.averageReview < 4 %}-half-o{% endif %}"></i>
            <i class="fa fa-star{% if product.averageReview < 4.5 %}-o{% elif product.averageReview >= 4.5 and product.averageReview < 5 %}-half-o{% endif %}"></i>
        <span>{{ product.countReview }} reviews</span>
        </span>
    </div>
</header>
{% for review in reviews %}
	<article class="box mb-3">
		<div class="icontext w-100">
			<div class="text">
				<span class="date text-muted float-md-right">{{ review.updated_at }} </span>
				<h6 class="mb-1">{{ review.user.full_name }} </h6>
				<div class="rating-star">
                    <span>
                        <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o{% endif %}"></i>
                        <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o{% endif %}"></i>
                        <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o{% endif %}"></i>
                        <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o{% endif %}"></i>
                        <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o{% endif %}"></i>
                    </span>
                </div>
			</div>
		</div> <!-- icontext.// -->
		<div class="mt-3">
            <h5>{{ review.subject }}</h5>
			<p>
				{{ review.review }}
			</p>	
		</div>
	</article>
{% endfor %}
	

	</div> <!-- col.// -->
</div> <!-- row.// -->


</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}
</html>