GreatKart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),

    # ORDERS
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('increase/<int:cart_item_id>', views.increase, name='increase'),
    path('remove_cart/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('checkout/', views.checkout, name='checkout')
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('place_order/', views.place_order, name='place_order'),
    path('payments/', views.payments, name='payments'),
    path('order_complete/', views.order_complete, name='order_complete')
]

store/urls.py
from django.urls import path
from . import views


app_name = 'store'
urlpatterns = [
    path('', views.store, name='store'),
    path('search/', views.search, name='search'),
    path('<slug:category_slug>/', views.store, name='products_by_category'),
    path('<slug:category_slug>/<slug:product_slug>', views.product_detail, name='product_detail'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),
]

orders/models.py
from django.db import models
from accounts.models import Account
from store.models import Product, Variations
# Create your models here.


class Payment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=100)
    payment_method = models.CharField(max_length=100)
    amount_paid = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.payment_id


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
    )

    user = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    order_number = models.CharField(max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    email = models.EmailField(max_length=50)
    address_line_1 = models.CharField(max_length=100)
    address_line_2 = models.CharField(max_length=100, blank=True)
    country = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    order_note = models.CharField(max_length=150, blank=True)
    order_total = models.FloatField()
    tax = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(max_length=20, blank=True)
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'

    def __str__(self):
        return self.first_name

    def sub_total(self):
        return round((self.order_total - self.tax), 2)


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variations, blank=True)
    quantity = models.PositiveIntegerField()
    product_price = models.FloatField()
    ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def sub_total(self):
        return round((self.product_price * self.quantity), 2)

    def __str__(self):
        return self.product.product_name

orders/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'first_name',
            'last_name',
            'phone',
            'email',
            'address_line_1',
            'address_line_2',
            'country',
            'state',
            'city',
            'order_note',
        ]

orders/views.py
import datetime
import json

from django.shortcuts import render, redirect
from carts.models import Cart_item
from .forms import OrderForm
from .models import Order, Payment, OrderProduct
from store.models import Product
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.http import JsonResponse


def payments(request):
    body = json.loads(request.body)
    order = Order.objects.get(user=request.user, is_ordered=False, order_number=body['orderID'])

    # Store transaction details inside Payment model
    payment = Payment(
        user=request.user,
        payment_id=body['transID'],
        payment_method=body['payment_method'],
        amount_paid=order.order_total,
        status=body['status'],
    )
    payment.save()
    order.payment = payment
    order.is_ordered = True
    order.save()

    # Move the cart items to OrderProduct table
    cart_items = Cart_item.objects.filter(user=request.user)
    for item in cart_items:
        order_product = OrderProduct()
        order_product.order_id = order.id
        order_product.payment = payment
        order_product.user_id = request.user.id
        order_product.product_id = item.product_id
        order_product.quantity = item.quantity
        order_product.product_price = item.product.price
        order_product.ordered = True
        order_product.save()

        cart_item = Cart_item.objects.get(id=item.id)
        product_variation = cart_item.variations.all()
        order_product = OrderProduct.objects.get(id=order_product.id)
        order_product.variations.set(product_variation)
        order_product.save()

        # Reduce the quantity of the sold products
        product = Product.objects.get(id=item.product_id)
        product.stock -= item.quantity
        product.save()

    # Clear the cart
    Cart_item.objects.filter(user=request.user).delete()

    # Send order received email to customer
    mail_subject = 'Thank you for your order!'
    message = render_to_string('orders/order_received_email.html', {
        'user': request.user,
        'order': order,
    })
    to_email = request.user.email
    send_email = EmailMessage(mail_subject, message, to=[to_email])
    send_email.send()

    # Send order number and transaction id back to sendData method via JsonResponse
    data = {
        'order_number': order.order_number,
        'transID': payment.payment_id,
    }
    return JsonResponse(data)


def place_order(request):
    current_user = request.user
    # If there are no cart_items redirect the user to the store page
    cart_items = Cart_item.objects.filter(user=current_user)
    cart_count = cart_items.count()
    if cart_count <= 0:
        return redirect('store:store')
    total = 0
    quantity = 0
    for cart_item in cart_items:
        total += round((cart_item.product.price * cart_item.quantity), 2)
        quantity += cart_item.quantity
    tax = round(((2 * total) / 100), 2)
    grand_total = round(total + tax, 2)

    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            # Store all the billing information inside Order table\
            data = Order()
            data.user = current_user
            data.first_name = form.cleaned_data['first_name']
            data.last_name = form.cleaned_data['last_name']
            data.phone = form.cleaned_data['phone']
            data.email = form.cleaned_data['email']
            data.address_line_1 = form.cleaned_data['address_line_1']
            data.address_line_2 = form.cleaned_data['address_line_2']
            data.country = form.cleaned_data['country']
            data.state = form.cleaned_data['state']
            data.city = form.cleaned_data['city']
            data.order_note = form.cleaned_data['order_note']
            data.order_total = grand_total
            data.tax = tax
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()
            # Generate order number
            yr = int(datetime.date.today().strftime('%Y'))
            dt = int(datetime.date.today().strftime('%d'))
            mt = int(datetime.date.today().strftime('%m'))
            d = datetime.date(yr, mt, dt)
            current_date = d.strftime('%Y%d%m')
            order_number = current_date + str(data.id)
            data.order_number = order_number
            data.save()

            order = Order.objects.get(user=current_user, is_ordered=False, order_number=order_number)
            context = {
                'order': order,
                'cart_items': cart_items,
                'total': total,
                'tax': tax,
                'grand_total': grand_total,
            }
            return render(request, 'orders/payments.html', context)
    return render(request, 'orders/place-order.html')


def order_complete(request):
    order_number = request.GET['order_number']
    order_products = OrderProduct.objects.filter(user=request.user, order__order_number=order_number)
    order = Order.objects.get(order_number=order_number)
    context = {
        'order_products': order_products,
        'order': order,
    }
    return render(request, 'orders/order_complete.html', context)

templates/orders/order_complete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container" style="margin-top: 50px;">
    <center><i class="fas fa-check-circle" style="font-size: 72px;margin-bottom: 20px;color: #28A745;"></i></center>
    <h2 class="text-center">Payment Successful</h2>
	<br>
	<div class="text-center">
		<a href="{% url 'store:store' %}" class="btn btn-success">Shop more</a>
	</div>
</div>

<div class="container" style="margin: 0 auto;width: 50%;padding: 50px;background: #f1f1f1;margin-top: 50px;margin-bottom: 50px;">
    <div class="row invoice row-printable">
        <div class="col-md-12">
            <!-- col-lg-12 start here -->
            <div class="panel panel-default plain" id="dash_0">
                <!-- Start .panel -->
                <div class="panel-body p30">
                    <div class="row">
                        <!-- Start .row -->
                        <div class="col-lg-6">
                            <!-- col-lg-6 start here -->
                            <div class="invoice-logo"><img src="{% static '/images/logo.png' %}" alt="Invoice logo" style="max-height: 40px;"></div>
                        </div>
                        <!-- col-lg-6 end here -->
                        <div class="col-lg-6">
                            <!-- col-lg-6 start here -->
                            <div class="invoice-from">
                                <ul class="list-unstyled text-right">
                                    <li><strong>Invoiced To</strong></li>
                                    <li>{{ order.full_name }}</li>
                                    <li>{{ order.full_address }}</li>
                                    <li>{{ order.city }}, {{ order.state }}</li>
                                    <li>{{ order.country }}</li>
                                </ul>
                            </div>
                        </div>
                        <!-- col-lg-6 end here -->
                        <div class="col-lg-12">
                            <!-- col-lg-12 start here -->
                            <div class="invoice-details mt25">
                                <div class="well">
                                    <ul class="list-unstyled mb0">
                                        <li><strong>Order</strong> #{{ order.order_number }}</li>
                                        <li><strong>Transaction</strong> #{{ order.payment.payment_id }}</li>
                                        <li><strong>Order Date:</strong> {{ order.payment.created_at }}</li>
                                        <li><strong>Status:</strong> PAID</li>
                                    </ul>
                                </div>
                            </div>
                           
                            <div class="invoice-items">
                                <div class="table-responsive" style="overflow: hidden; outline: none;" tabindex="0">
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th class="per70 text-center">Description</th>
                                                <th class="per5 text-center">Qty</th>
                                                <th class="per25 text-center">Total</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for product in order_products %}
                                            <tr>
                                                <td>{{ product.product.product_name }}
                                                <br><p class="text-muted small">
                                                    {% if product.variations.all %}
                                                        {% for item in product.variations.all %}
                                                            {{ item.variation_category | capfirst }} : {{ item.variation_value | capfirst }} <br>
                                                        {% endfor %}
                                                    {% endif %}
                                                    </p>
                                                </td>
                                                <td class="text-center">{{ product.quantity }}</td>
                                                <td class="text-center">
                                                    <div class="price-wrap">
                                                        <var class="price">${{ product.sub_total }}</var><br>
                                                        <small class="text-muted"> ${{ product.product_price }} each </small>
                                                    </div>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th colspan="2" class="text-right">Sub Total:</th>
                                                <th class="text-center">${{ order.sub_total }} USD</th>
                                            </tr>
                                            <tr>
                                                <th colspan="2" class="text-right">Tax:</th>
                                                <th class="text-center">${{ order.tax }} USD</th>
                                            </tr>
                                            
                                            <tr>
                                                <th colspan="2" class="text-right">Grand Total:</th>
                                                <th class="text-center">${{ order.order_total }} USD</th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                            <div class="invoice-footer mt25">
                                <p class="text-center">Thank you for shopping with us!</p>
                            </div>
                        </div>
                        <!-- col-lg-12 end here -->
                    </div>
                    <!-- End .row -->
                </div>
            </div>
            <!-- End .panel -->
        </div>
        <!-- col-lg-12 end here -->
    </div>
    </div>
{% endblock %}

templates/orders/order_received_email.html
{% autoescape off %}

Hi {{ user.first_name }},

Your order has been received!

Order Number: {{ order.order_number }}

If you think it's not you, please ignore this email!

{% endautoescape %}

templates/orders/payments.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
<h4 class="text-center mb-10">Review your order and make payment</h4>
<div class="row">
	<aside class="col-lg-8">
        <div class="card">
          <h5 class="card-header">Billing Address</h5>
          <div class="card-body">
              <p class="card-text mb-0">{{ order.full_name }}</p>
              <p class="card-text mb-0">{{ order.email }}</p>
              <p class="card-text mb-0">{{ order.phone }}</p>
              <p class="card-text mb-0">{{ order.full_address }}</p>
              <p class="card-text mb-0">{{ order.city }}, {{ order.state }}</p>
              <p class="card-text mb-0">{{ order.country }}</p>
              {% if order.order_note %}
                <b>Order Note: {{ order.order_note }}</b>
              {% endif %}
          </div>
        </div>
        <div class="card">
          <h5 class="card-header">Payment Method</h5>
          <div class="card-body">
            <p class="card-text">PayPal</p>
          </div>
        </div>
        <div class="card">
          <h5 class="card-header">Review Products</h5>
          <div class="card-body">
              <table class="table table-borderless table-shopping-cart">
                  <thead class="text-muted">
                  <tr class="small text-uppercase">
                    <th scope="col">Product</th>
                    <th scope="col" width="120">Quantity</th>
                    <th scope="col" width="120">Price</th>

                  </tr>
                  </thead>
                  <tbody>

                  {% for cart_item in cart_items %}
                  <tr>
                    <td>
                        <figure class="itemside align-items-center">
                            <div class="aside"><img src="{{ cart_item.product.images.url }}" class="img-sm"></div>
                            <figcaption class="info">
                                <a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.product_name }}</a>
                                <p class="text-muted small">
                                    {% if cart_item.variations.all %}
                                        {% for item in cart_item.variations.all %}
                                            {{ item.variation_category | capfirst }} : {{ item.variation_value | capfirst }} <br>
                                        {% endfor %}
                                    {% endif %}
                                </p>
                            </figcaption>
                        </figure>
                    </td>
                    <td>
                        <!-- col.// -->
                                <label for="">{{cart_item.quantity}}</label>
                    </td>
                    <td>
                        <div class="price-wrap">
                            <var class="price">$ {{ cart_item.sub_total }}</var>
                            <small class="text-muted"> $ {{ cart_item.product.price }} each </small>
                        </div> <!-- price-wrap .// -->
                    </td>

                  </tr>
                  {% endfor %}

                  </tbody>
              </table>
          </div>
        </div>

	</aside> <!-- col.// -->
	<aside class="col-lg-4">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">${{ total }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right"> ${{ tax }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Total:</dt>
			  <dd class="text-right text-dark b"><strong>${{ grand_total }}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="{% static '/images/misc/payments.png' %}" height="26">
			</p>
			<div id="paypal-button-container">

            </div>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
<script>

	function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

	var amount = "{{ grand_total }}"
	var url = "{% url 'orders:payments' %}"
	var csrftoken = getCookie('csrftoken');
	var orderID = "{{order.order_number}}"
	var payment_method = 'PayPal'
	var redirect_url = "{% url 'orders:order_complete' %}"
	// Render the PayPal button into #paypal-button-container
	paypal.Buttons({

		style: {
			color: 'blue',
			shape: 'rect',
			label: 'pay',
			height: 40
		},

		// Set up the transaction
		createOrder: function(data, actions) {
			return actions.order.create({
				purchase_units: [{
					amount: {
						value: amount,
					}
				}]
			});
		},

		// Finalize the transaction
		onApprove: function(data, actions) {
			return actions.order.capture().then(function(details) {
				// Show a success message to the buyer
				console.log(details);
				sendData();
				function sendData(){
					fetch(url, {
						method : "POST",
						headers: {
							"Content-type": "application/json",
							"X-CSRFToken": csrftoken,
						},
						body: JSON.stringify({
							orderID: orderID,
							transID: details.id,
							payment_method: payment_method,
							status: details.status,
						}),
					})
				  .then((response) => response.json())
				  .then((data) => {
						window.location.href = redirect_url + '?order_number='+data.orderID+'&payment_id='+data.transID;
					});
				}
			});
		}


	}).render('#paypal-button-container');
</script>
{% endblock %}